/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.iesellago.tema2.MascotasApp.View;

import es.iesellago.tema2.MascotasApp.Controller.ConsultasPaciente;
import es.iesellago.tema2.MascotasApp.Model.Paciente;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 * Panel donde se va a visualizar todos los pacientes mediante una consulta y
 * serán representados los datos en una tabla.
 *
 * @author mauri_
 */
public class TablaListaPacientes extends javax.swing.JPanel {

    /**
     * Creates new form LimiteRegistros
     */
    public TablaListaPacientes() {
        initComponents();
        iniciarTablaListaUsuarios();

    }

    /**
     * Método que inicia la tabla, no requiere de parámetros
     * 
     */
    private void iniciarTablaListaUsuarios() {
        //Se instancia la consulta y el modelo de la tabla por defecto.
        ConsultasPaciente consulta = new ConsultasPaciente();
        DefaultTableModel modelo = new DefaultTableModel();
        ArrayList<Paciente> listaPacientes = consulta.listaMascotas();
        //Definir columnas
        modelo.addColumn("ID Mascota");
        modelo.addColumn("Alias Mascota");
        modelo.addColumn("Especie");
        modelo.addColumn("Raza");
        modelo.addColumn("Color de pelo");
        modelo.addColumn("Fecha de Nacimiento");
        modelo.addColumn("Vacunaciones");

        //instertar datos
        for (Paciente paciente : listaPacientes) {
            modelo.addRow(new Object[]{
                paciente.getIdMascota(),
                paciente.getAliasMascota(),
                paciente.getEspecie(),
                paciente.getRaza(),
                paciente.getColorPelo(),
                paciente.getFechaNacimiento(),
                paciente.getVacunaciones()

            });

        }

        //establecer el modelo creado.
        tbTabla.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbTabla = new javax.swing.JTable();

        tbTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbTabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTabla;
    // End of variables declaration//GEN-END:variables
}
