/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.iesellago.tema2.MascotasApp.View;

import es.iesellago.tema2.MascotasApp.Controller.ConsultasPaciente;
import es.iesellago.tema2.MascotasApp.Model.Paciente;
import es.iesellago.tema2.MascotasApp.Model.Peso;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *Se va a insertar la tabla según el criterio de límite de registros.
 * 
 * @author mauri_
 */
public class TablaTopMasLigeros extends javax.swing.JPanel {

    /**
     * Creates new form LimiteRegistros
     */
    public TablaTopMasLigeros() {
        initComponents();
        
    }
    
    
    /**
     * Método que inicia la tabla con los datos que se necesitan.
     */
    
    private void iniciarTablaTopMasLigeros() {
        ConsultasPaciente consulta = new ConsultasPaciente();
        DefaultTableModel modelo = new DefaultTableModel();
        ArrayList<Peso> topMasLigeros = consulta.topMasLigeros(returnLimite());

        modelo.addColumn("ID Mascota");
        modelo.addColumn("ID Peso");
        modelo.addColumn("Peso");

        for (Peso peso : topMasLigeros) {
            modelo.addRow(new Object[]{
                peso.getIdMascota(),
                peso.getIdPeso(),
                peso.getPeso()
            });
        }

        tbTabla.setModel(modelo);
    }
     
    /**
     * Metodo que establece el límite elegido por el usuario.
     * @return El límite que se elige.
     */
     private int returnLimite(){
        int limite = Integer.parseInt(txtLimite.getText());
        return limite;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbTabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtLimite = new javax.swing.JTextField();
        btnMostrarResultados = new javax.swing.JButton();

        tbTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbTabla);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Introduzca limite de registros");

        btnMostrarResultados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMostrarResultados.setText("<html>Mostrar Resultados<br>Top Más Ligeros</html>");
        btnMostrarResultados.setAlignmentY(0.0F);
        btnMostrarResultados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMostrarResultados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMostrarResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarResultadosMouseClicked(evt);
            }
        });
        btnMostrarResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarResultadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMostrarResultados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnMostrarResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarResultadosMouseClicked
        iniciarTablaTopMasLigeros();
    }//GEN-LAST:event_btnMostrarResultadosMouseClicked

    private void btnMostrarResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarResultadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarResultadosActionPerformed


    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarResultados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTabla;
    private javax.swing.JTextField txtLimite;
    // End of variables declaration//GEN-END:variables
}
