/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.iesellago.tema2.MascotasApp.View;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 * Este JPanel dispone de varios botones y otro panel, donde se visualizará lo
 * que accione cada botón.
 *
 * @author mauri_
 */
public class VentanaUpdate extends javax.swing.JPanel {

    /**
     * Creates new form VentanaInsercciones
     */
    public VentanaUpdate() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnUpdateVacuna = new javax.swing.JButton();
        btnUpdatePaciente = new javax.swing.JButton();
        btnUpdatePeso = new javax.swing.JButton();
        pnFormInserciones = new javax.swing.JPanel();

        setBackground(new java.awt.Color(204, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(755, 400));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ACTUALIZACIÓN DE DATOS");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);

        btnUpdateVacuna.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUpdateVacuna.setText("ACTUALIZAR VACUNA");
        btnUpdateVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateVacunaActionPerformed(evt);
            }
        });

        btnUpdatePaciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUpdatePaciente.setText("ACTUALIZAR PACIENTE");
        btnUpdatePaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdatePacienteMouseClicked(evt);
            }
        });
        btnUpdatePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePacienteActionPerformed(evt);
            }
        });

        btnUpdatePeso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUpdatePeso.setText("ACTUALIZAR PESO");
        btnUpdatePeso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdatePesoMouseClicked(evt);
            }
        });

        pnFormInserciones.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout pnFormInsercionesLayout = new javax.swing.GroupLayout(pnFormInserciones);
        pnFormInserciones.setLayout(pnFormInsercionesLayout);
        pnFormInsercionesLayout.setHorizontalGroup(
            pnFormInsercionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnFormInsercionesLayout.setVerticalGroup(
            pnFormInsercionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnFormInserciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpdatePaciente)
                                .addGap(44, 44, 44)
                                .addComponent(btnUpdateVacuna)
                                .addGap(13, 13, 13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(btnUpdatePeso)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateVacuna)
                    .addComponent(btnUpdatePeso)
                    .addComponent(btnUpdatePaciente))
                .addGap(29, 29, 29)
                .addComponent(pnFormInserciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdatePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePacienteActionPerformed

    }//GEN-LAST:event_btnUpdatePacienteActionPerformed

    private void btnUpdatePacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdatePacienteMouseClicked
        FormularioUpdatePaciente formUpdatePaciente = new FormularioUpdatePaciente();
        insertarPanel(formUpdatePaciente);
    }//GEN-LAST:event_btnUpdatePacienteMouseClicked

    private void btnUpdateVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateVacunaActionPerformed
        FormularioUpdateVacuna formUpdateVacuna = new FormularioUpdateVacuna();
        insertarPanel(formUpdateVacuna);

    }//GEN-LAST:event_btnUpdateVacunaActionPerformed

    private void btnUpdatePesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdatePesoMouseClicked
        FormularioUpdatePeso formUpdatePeso = new FormularioUpdatePeso();
        insertarPanel(formUpdatePeso);
    }//GEN-LAST:event_btnUpdatePesoMouseClicked

    /**
     * Método de inicialización de panel.
     * 
     * @param panel Panel que queremos visualizar.
     */
    public void insertarPanel(JPanel panel) {
        int ancho = pnFormInserciones.getWidth();
        int alto = pnFormInserciones.getHeight();
        panel.setSize(ancho, alto);
        panel.setLocation(0, 0);
        pnFormInserciones.removeAll();
        pnFormInserciones.add(panel, BorderLayout.CENTER);
        pnFormInserciones.revalidate();
        pnFormInserciones.repaint();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdatePaciente;
    private javax.swing.JButton btnUpdatePeso;
    private javax.swing.JButton btnUpdateVacuna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnFormInserciones;
    // End of variables declaration//GEN-END:variables
}
