/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.iesellago.tema2.MascotasApp.View;

import es.iesellago.tema2.MascotasApp.Controller.ConsultasPaciente;
import es.iesellago.tema2.MascotasApp.Model.Paciente;
import es.iesellago.tema2.MascotasApp.Model.Peso;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * Este JPanel dispone de varios botones y otro panel, donde se visualizará lo
 * que accione cada botón.
 *
 * @author mauri_
 */
public class VentanaConsultas extends javax.swing.JPanel {

    /**
     * Creates new form VentanaInsercciones
     */
    public VentanaConsultas() {
        initComponents();

    }

    /**
     * Función de inicialización de panel.
     * @param panel El panel que se quiere visualizar.
     */
    private void iniciarPanel(JPanel panel) {

        panel.setSize(715, 240);
        panel.setLocation(0, 0);
        pnVentana.removeAll();
        pnVentana.add(panel, BorderLayout.CENTER);
        pnVentana.revalidate();
        pnVentana.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnTopMasVacunas = new javax.swing.JButton();
        btnListaPacientes = new javax.swing.JButton();
        btnTopMasPesados = new javax.swing.JButton();
        btnRecuentoPorEspecie = new javax.swing.JButton();
        btnTopLigeros = new javax.swing.JButton();
        pnLimiteRegistros = new javax.swing.JPanel();
        pnVentana = new javax.swing.JPanel();

        setBackground(new java.awt.Color(204, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(755, 400));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONSULTA DE DATOS");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);

        btnTopMasVacunas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTopMasVacunas.setText("TOP MÁS VACUNAS");
        btnTopMasVacunas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTopMasVacunasMouseClicked(evt);
            }
        });
        btnTopMasVacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopMasVacunasActionPerformed(evt);
            }
        });

        btnListaPacientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnListaPacientes.setText("LISTAR PACIENTES");
        btnListaPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListaPacientesMouseClicked(evt);
            }
        });
        btnListaPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaPacientesActionPerformed(evt);
            }
        });

        btnTopMasPesados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTopMasPesados.setText("TOP MÁS PESADOS");
        btnTopMasPesados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTopMasPesadosMouseClicked(evt);
            }
        });
        btnTopMasPesados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopMasPesadosActionPerformed(evt);
            }
        });

        btnRecuentoPorEspecie.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRecuentoPorEspecie.setText("RECUENTO POR ESPECIE");
        btnRecuentoPorEspecie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecuentoPorEspecieMouseClicked(evt);
            }
        });
        btnRecuentoPorEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuentoPorEspecieActionPerformed(evt);
            }
        });

        btnTopLigeros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTopLigeros.setText("TOP MÁS LIGEROS");
        btnTopLigeros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTopLigerosMouseClicked(evt);
            }
        });
        btnTopLigeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopLigerosActionPerformed(evt);
            }
        });

        pnLimiteRegistros.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout pnLimiteRegistrosLayout = new javax.swing.GroupLayout(pnLimiteRegistros);
        pnLimiteRegistros.setLayout(pnLimiteRegistrosLayout);
        pnLimiteRegistrosLayout.setHorizontalGroup(
            pnLimiteRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnLimiteRegistrosLayout.setVerticalGroup(
            pnLimiteRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnVentana.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout pnVentanaLayout = new javax.swing.GroupLayout(pnVentana);
        pnVentana.setLayout(pnVentanaLayout);
        pnVentanaLayout.setHorizontalGroup(
            pnVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnVentanaLayout.setVerticalGroup(
            pnVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTopMasVacunas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListaPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnTopLigeros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnTopMasPesados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnRecuentoPorEspecie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pnLimiteRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecuentoPorEspecie)
                    .addComponent(btnListaPacientes)
                    .addComponent(btnTopMasPesados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnLimiteRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTopMasVacunas)
                        .addComponent(btnTopLigeros)))
                .addGap(18, 18, 18)
                .addComponent(pnVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnListaPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaPacientesActionPerformed

    }//GEN-LAST:event_btnListaPacientesActionPerformed

    private void btnListaPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaPacientesMouseClicked

        TablaListaPacientes vLP = new TablaListaPacientes();
        iniciarPanel(vLP);


    }//GEN-LAST:event_btnListaPacientesMouseClicked

    private void btnTopMasPesadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopMasPesadosActionPerformed


    }//GEN-LAST:event_btnTopMasPesadosActionPerformed

    private void btnTopMasVacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopMasVacunasActionPerformed

    }//GEN-LAST:event_btnTopMasVacunasActionPerformed

    private void btnTopMasVacunasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTopMasVacunasMouseClicked
        TablaTopMasVacunas tablaTMV = new TablaTopMasVacunas();
        iniciarPanel(tablaTMV);


    }//GEN-LAST:event_btnTopMasVacunasMouseClicked

    private void btnTopMasPesadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTopMasPesadosMouseClicked

        TablaTopMasPesados tablaTMP = new TablaTopMasPesados();
        iniciarPanel(tablaTMP);


    }//GEN-LAST:event_btnTopMasPesadosMouseClicked

    private void btnRecuentoPorEspecieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecuentoPorEspecieMouseClicked
        PanelRecuentoPorEspecie recuento = new PanelRecuentoPorEspecie();
        iniciarPanel(recuento);
    }//GEN-LAST:event_btnRecuentoPorEspecieMouseClicked

    private void btnRecuentoPorEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuentoPorEspecieActionPerformed

    }//GEN-LAST:event_btnRecuentoPorEspecieActionPerformed

    private void btnTopLigerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTopLigerosMouseClicked
        TablaTopMasLigeros tablaTML = new TablaTopMasLigeros();
        iniciarPanel(tablaTML);

    }//GEN-LAST:event_btnTopLigerosMouseClicked

    private void btnTopLigerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopLigerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTopLigerosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListaPacientes;
    private javax.swing.JButton btnRecuentoPorEspecie;
    private javax.swing.JButton btnTopLigeros;
    private javax.swing.JButton btnTopMasPesados;
    private javax.swing.JButton btnTopMasVacunas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnLimiteRegistros;
    private javax.swing.JPanel pnVentana;
    // End of variables declaration//GEN-END:variables
}
