/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package es.iesellago.tema2.MascotasApp.View;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 * Este JPanel dispone de varios botones y otro panel, donde se visualizará lo
 * que accione cada botón.
 *
 * @author mauri_
 */
public class VentanaInsercciones extends javax.swing.JPanel {

    /**
     * Creates new form VentanaInsercciones
     */
    public VentanaInsercciones() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnInsertarVacuna = new javax.swing.JButton();
        btnInsertaPaciente = new javax.swing.JButton();
        btnInsertarPeso = new javax.swing.JButton();
        pnFormInserciones = new javax.swing.JPanel();
        btnInsertaPacientePorArchivo = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(755, 400));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INSERCCION DE DATOS");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);

        btnInsertarVacuna.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnInsertarVacuna.setText("INSERTAR VACUNA");
        btnInsertarVacuna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarVacunaMouseClicked(evt);
            }
        });
        btnInsertarVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarVacunaActionPerformed(evt);
            }
        });

        btnInsertaPaciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnInsertaPaciente.setText("INSERTAR PACIENTE");
        btnInsertaPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertaPacienteMouseClicked(evt);
            }
        });
        btnInsertaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertaPacienteActionPerformed(evt);
            }
        });

        btnInsertarPeso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnInsertarPeso.setText("INSERTAR PESO");
        btnInsertarPeso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarPesoMouseClicked(evt);
            }
        });

        pnFormInserciones.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout pnFormInsercionesLayout = new javax.swing.GroupLayout(pnFormInserciones);
        pnFormInserciones.setLayout(pnFormInsercionesLayout);
        pnFormInsercionesLayout.setHorizontalGroup(
            pnFormInsercionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnFormInsercionesLayout.setVerticalGroup(
            pnFormInsercionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        btnInsertaPacientePorArchivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInsertaPacientePorArchivo.setText("INSERTAR PACIENTE POR ARCHIVO ");
        btnInsertaPacientePorArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertaPacientePorArchivoMouseClicked(evt);
            }
        });
        btnInsertaPacientePorArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertaPacientePorArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnFormInserciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnInsertaPacientePorArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInsertaPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnInsertarVacuna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnInsertarPeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(53, 53, 53))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarVacuna)
                    .addComponent(btnInsertaPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarPeso)
                    .addComponent(btnInsertaPacientePorArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(pnFormInserciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertaPacienteActionPerformed

    }//GEN-LAST:event_btnInsertaPacienteActionPerformed

    private void btnInsertaPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertaPacienteMouseClicked
        FormularioInserccionPaciente formInsertPaciente = new FormularioInserccionPaciente();
        insertarPanel(formInsertPaciente);

    }//GEN-LAST:event_btnInsertaPacienteMouseClicked

    private void btnInsertarVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarVacunaActionPerformed


    }//GEN-LAST:event_btnInsertarVacunaActionPerformed

    private void btnInsertarPesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarPesoMouseClicked
        FormularioInserccionPeso formInsertPeso = new FormularioInserccionPeso();
        insertarPanel(formInsertPeso);


    }//GEN-LAST:event_btnInsertarPesoMouseClicked

    private void btnInsertaPacientePorArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertaPacientePorArchivoMouseClicked
        FormularioInsertarPacientePorArchivo formInsertPorArchivo = new FormularioInsertarPacientePorArchivo();
        insertarPanel(formInsertPorArchivo);


    }//GEN-LAST:event_btnInsertaPacientePorArchivoMouseClicked

    private void btnInsertaPacientePorArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertaPacientePorArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertaPacientePorArchivoActionPerformed

    private void btnInsertarVacunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarVacunaMouseClicked
        FormularioInserccionVacuna formInsertVacuna = new FormularioInserccionVacuna();
        insertarPanel(formInsertVacuna);
    }//GEN-LAST:event_btnInsertarVacunaMouseClicked

    
    /**
     * Metodo de incialización de panel.
     * @param panel El panel que se quiere visualizar.
     */
    public void insertarPanel(JPanel panel) {
        int ancho = pnFormInserciones.getWidth();
        int alto = pnFormInserciones.getHeight();
        panel.setSize(ancho, alto);
        panel.setLocation(0, 0);
        pnFormInserciones.removeAll();
        pnFormInserciones.add(panel, BorderLayout.CENTER);
        pnFormInserciones.revalidate();
        pnFormInserciones.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertaPaciente;
    private javax.swing.JButton btnInsertaPacientePorArchivo;
    private javax.swing.JButton btnInsertarPeso;
    private javax.swing.JButton btnInsertarVacuna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnFormInserciones;
    // End of variables declaration//GEN-END:variables
}
